plan_urls:
  - https://provider.carefirst.com/carefirst-resources/machine-readable/Plans.json
drug_urls:
  - https://provider.carefirst.com/carefirst-resources/machine-readable/Drugs_1.json
  - https://provider.carefirst.com/carefirst-resources/machine-readable/Drugs_2.json
  - https://provider.carefirst.com/carefirst-resources/machine-readable/Drugs_3.json
  - https://provider.carefirst.com/carefirst-resources/machine-readable/Drugs_4.json
  - https://provider.carefirst.com/carefirst-resources/machine-readable/Drugs_5.json
max_drugs_per_plan: 1000
